version: "3.5"
services:
  engine:
    image: 5minds/engine:13.4.6
    ports:
      - 8000:8000
    volumes:
      - ./.processcube/engine/config/config.json:/etc/engine/config/config.json:ro
      - ./.processcube/engine/db:/root/.config/AtlasEngineFullstackServer/databases:rw
      - ./processes:/processes:ro
    command: --seed-dir=/processes --port 8000
    environment:
      CONFIG_PATH: /etc/engine/config/config.json

  portal:
    image: 5minds/portal:3.9.0-beta.1
    volumes:
      - ./.processcube/portal/theme.css:/etc/portal/config/theme.css:ro
      - ./.processcube/portal/config.json:/etc/portal/config/config.json:ro
      - ./.processcube/portal/assets:/etc/portal/config/assets:ro
      - ./.processcube/portal/translation:/etc/portal/config/translation:ro
    command: "--config-path /etc/portal/config/config.json --theme /etc/portal/config/theme.css --assets /etc/portal/config/assets"
    ports:
      - 8082:8082

  app:
    image: 5minds/processcube_project
    build:
      context: ./
      dockerfile: apps/Zahlenraten.Intermediate/Dockerfile
    volumes:
      - ./apps/Zahlenraten.Intermediate/frontend/src/config/config.json:/apps/Zahlenraten.Intermediate/wwwroot/config.json
      - ./apps/Zahlenraten.Intermediate/Properties/:/apps/Zahlenraten.Intermediate/Properties/
      - ./apps/Zahlenraten.Intermediate/appsettings.${APPENVIRONMENT:-Development}.json:/apps/Zahlenraten.Intermediate/appsettings.json
      - ./apps/Zahlenraten.Intermediate/Program.cs:/apps/Zahlenraten.Intermediate/Program.cs
      - ./apps/Zahlenraten.Intermediate/Worker/:/apps/Zahlenraten.Intermediate/Worker/
    ports:
      - 5111:5111
    working_dir: /apps/Zahlenraten.Intermediate
    environment:
      - APPSETTINGS=${APPSETTINGS}
    command: dotnet run

  frontend:
    image: 5minds/processcube_project
    volumes:
      - ./apps/Zahlenraten.Intermediate/frontend/public/:/apps/Zahlenraten.Intermediate/frontend/public/
      - ./apps/Zahlenraten.Intermediate/frontend/src/:/apps/Zahlenraten.Intermediate/frontend/src/
      - ./apps/Zahlenraten.Intermediate/frontend/.env:/apps/Zahlenraten.Intermediate/frontend/.env
      - ./apps/Zahlenraten.Intermediate/frontend/.env.development:/apps/Zahlenraten.Intermediate/frontend/.env.development
      - ./apps/Zahlenraten.Intermediate/frontend/aspnetcore-https.js:/apps/Zahlenraten.Intermediate/frontend/aspnetcore-https.js
      - ./apps/Zahlenraten.Intermediate/frontend/aspnetcore-react.js:/apps/Zahlenraten.Intermediate/frontend/aspnetcore-react.js
      - ./apps/Zahlenraten.Intermediate/frontend/tsconfig.json:/apps/Zahlenraten.Intermediate/frontend/tsconfig.json
    working_dir: /apps/Zahlenraten.Intermediate/frontend/
    command: npm start
    ports:
      - 3000:3000
      - 9229:9229
